version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
  web:
    build: .
    links:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - '3000:3000'
